baseURL = 'https://kaj.arno.fi/'
languageCode = 'sv-fi'
title = 'Kaj Arnö &#8211; IT-företagare. Idrottshedonist. Fritänkare.'
theme = 'hugo-xmag'
buildDrafts = false
paginate = 100

[permalinks]
  post = '/:filename/'
  categories = "/k/:title/"

[params]
  description = "Kaj Arnö - IT-företagare. Idrottshedonist. Fritänkare."
  images = ['/cropped-2018-05-21_IMG_7781-6.jpg']
  footer = "&copy; Kaj Arnö 2023 | [Twitter](https://twitter.com/kajarno) | [Facebook](https://facebook.com/kajarno) | [LinkedIn](https://linkedin.com/in/kajarno) | [Instagram](https://instagram.com/kajarno)"
  summary_length = 250
  favicon = "/favicon.ico"

[menu]

  [[menu.main]]
  name = 'IT'
  url = '/it/'
  identifier = 'it'
  weight = 2

    [[menu.main]]
    name = 'MariaDB'
    url = '/k/mariadb/'
    identifier = 'mariadb'
    parent = 'it'
    weight = 1

    [[menu.main]]
    name = 'MySQL'
    url = '/k/mysql/'
    identifier = 'mysql'
    parent = 'it'
    weight = 2

    [[menu.main]]
    name = 'Medier'
    url = '/k/medier/'
    identifier = 'medier'
    parent = 'it'
    weight = 3

  [[menu.main]]
  name = 'Idrottshedonism'
  url = '/idrottshedonism/'
  identifier = 'idrottshedonism'
  weight = 3

    [[menu.main]]
    name = 'Springa'
    url = '/k/springa/'
    identifier = 'springa'
    parent = 'idrottshedonism'
    weight = 1

    [[menu.main]]
    name = 'Paddla'
    url = '/k/paddla/'
    identifier = 'paddla'
    parent = 'idrottshedonism'
    weight = 2

    [[menu.main]]
    name = 'Yoga'
    url = '/k/yoga/'
    identifier = 'yoga'
    parent = 'idrottshedonism'
    weight = 3

  [[menu.main]]
  name = 'Fritanke'
  url = '/fritanke/'
  identifier = 'fritanke'
  weight = 4

    [[menu.main]]
    name = 'Projekt Fredrika'
    url = '/k/projekt-fredrika/'
    identifier = 'projekt-fredrika'
    parent = 'fritanke'
    weight = 1

    [[menu.main]]
    name = 'Nagu'
    url = '/k/nagu/'
    identifier = 'nagu'
    parent = 'fritanke'
    weight = 2

    [[menu.main]]
    name = 'Tyskland'
    url = '/k/tyskland/'
    identifier = 'tyskland'
    parent = 'fritanke'
    weight = 3

    [[menu.main]]
    name = 'München'
    url = '/k/munchen/'
    identifier = 'munchen'
    parent = 'fritanke'
    weight = 4

    [[menu.main]]
    name = 'Politik'
    url = '/k/politik/'
    identifier = 'politik'
    parent = 'fritanke'
    weight = 5

    [[menu.main]]
    name = 'Musik'
    url = '/k/musik/'
    identifier = 'musik'
    parent = 'fritanke'
    weight = 6

    [[menu.main]]
    name = 'Frihet'
    url = '/k/frihet/'
    identifier = 'frihet'
    parent = 'fritanke'
    weight = 7
	
  [[menu.main]]
  name = 'Om'
  url = '/om/'
  identifier = 'om1'
  weight = 5

    [[menu.main]]
    name = 'Kaj'
    url = '/om/'
    identifier = 'om'
    parent = 'om1'
    weight = 1

    [[menu.main]]
    name = 'Ukraina'
    url = '/ukraina/'
    identifier = 'ukraina'
    parent = 'om1'
    weight = 2

    [[menu.main]]
    name = 'Nagu'
    url = '/nagu/'
    identifier = 'nagu'
    parent = 'om1'
    weight = 3

    [[menu.main]]
    name = 'Åbo Underrättelser'
    url = '/au/'
    identifier = 'au'
    parent = 'om1'
    weight = 4

    [[menu.main]]
    name = 'TFiF'
    url = '/tfif/'
    identifier = 'tfif'
    parent = 'om1'
    weight = 5

    [[menu.main]]
    name = 'Nato'
    url = '/nato/'
    identifier = 'nato'
    parent = 'om1'
    weight = 6
